<?php
/**
 * Description of ViewBitsHelper
 *
 * @author david
 */
App::uses('AppHelper','View/Helper');

class ViewBitsHelper extends AppHelper{
    
    /**
     * Will output a ViewBit to the page
     * @param array $bits A Cake array of ViewBits generated by the component
     * @param int $order The order number of the item you want to ouput
     * @return html
     */
    public function out(array $bits, $order = 1){
        return $bits[$order-1]['ViewBit']['content'];
    }
    
}

?>
